openapi: 3.0.3
info:
  title: user-service
  description: User Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /api/user-service/register:
    $ref: 'endpoint/CreateUser.yml'
  /api/user-service/login:
    $ref: 'endpoint/LoginUser.yml'
