openapi: 3.0.3
info:
  title: user-service
  description: User Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /:
    get:
      responses:
        200:
          description: OK
  /api/users:
    $ref: 'endpoint/CreateUser.yml'
