openapi: 3.0.3
info:
  title: user-service
  description: User Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /api/v1/user-service/public/register:
    $ref: 'endpoint/CreateUser.yml'
  /api/v1/user-service/public/token:
    $ref: 'endpoint/LoginUser.yml'
