openapi: 3.0.3
info:
  title: user-service
  description: User Service
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /api/users:
    post:
      tags:
        - User
      operationId: register
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        200:
          description: User created successfully

components:
  schemas:
    CreateUser:
      $ref: 'schemas/CreateUser.yml'