spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_test
    username: test_user
    password: test_password
    driverClassName: org.postgresql.Driver