name: Build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gebozhinov/parent:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Show current directory and files
        run: |
          pwd
          ls -la

      - name: Build with Gradle Wrapper
        run: ../../gradlew build