name: Build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gebozhinov/parent:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v4
        with:
          repository: ccexdev/parent
          token: ${{ secrets.GITHUB_TOKEN }}
          path: parent

      - name: Checkout user-service repository
        uses: actions/checkout@v4
        with:
          path: services/user-service

      - name: Replace user-service code in parent
        run: |
          rm -rf parent/services/user-service
          cp -r user-service parent/services/user-service

      - name: Show files
        run: |
          ls -la
          ls -la parent
          ls -la services/user-service

#      - name: Build with Gradle Wrapper
#        run: ./gradlew build

      - name: Build user-service
        run: |
          cd parent
          ./gradlew :services:user-service:build
