name: Build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gebozhinov/parent:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v4
        with:
          repository: ccexdev/parent
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show current directory and files
        run: |
          pwd
          ls -la
          ls -la ../../

      - name: Build with Gradle Wrapper 1
        run: ./gradlew build

      - name: Show current directory and files 2
        run: |
          pwd
          ls -la
          ls -la ../../

      - name: Build with Gradle Wrapper
        run: ./gradlew :services:user-service:build
