name: Build

on:
  pull_request:
    branches: ['main']

env:
  PARENT_REPO: ccexdev/parent
  PARENT_BRANCH: main
  SERVICE_NAME: user-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ env.SERVICE_NAME }} repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.SERVICE_NAME }}

      - name: Clone parent repo
        run: git clone --single-branch --branch ${{ env.PARENT_BRANCH }} https://github.com/${{ env.PARENT_REPO }} parent

      - name: Copy ${{ env.SERVICE_NAME }} into parent structure
        run: |
          mkdir -p parent/services
          rm -rf parent/services/${{ env.SERVICE_NAME }}
          cp -r ${{ env.SERVICE_NAME }} parent/services/${{ env.SERVICE_NAME }}

      - name: Build ${{ env.SERVICE_NAME }}
        run: |
          cd parent
          ./gradlew :services:${{ env.SERVICE_NAME }}:clean :services:${{ env.SERVICE_NAME }}:build
