name: Build

on:
  pull_request:
    branches: ['main']

env:
  PARENT_REPO: ccexdev/parent
  PARENT_BRANCH: main
  SERVICE_NAME: user-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PARENT_REPO }}
          ref: ${{ env.PARENT_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: parent

      - name: Checkout service repository
        uses: actions/checkout@v4
        with:
          path: service

#      - name: Copy service into parent modules
#        run: |
#          rm -rf parent/services/${{ env.SERVICE_NAME }}
#          cp -r service parent/services/${{ env.SERVICE_NAME }}

#      - name: Show files
#        run: |
#          ls -la parent/services/${{ env.SERVICE_NAME }}

      - name: Show files
        run: |
          ls -la

      - name: Build service (with/without tests)
        run: |
          cd parent
          ./gradlew :services:${{ env.SERVICE_NAME }}:clean :services:${{ env.SERVICE_NAME }}:build
